-- ═══════════════════════════════════════════════════════════════
-- GRACIOU — tabelas esperadas no Supabase (Postgres / schema public)
-- Arquivo: supabase/schema.sql
-- ═══════════════════════════════════════════════════════════════
--
-- Documento de referência: descreve o que o backend acessa via REST
-- (backend/repositorio.js). NÃO é executado automaticamente pelo app e
-- não contém credencial alguma.
--
-- Regras:
--   * valores de dinheiro ficam em CENTAVOS (integer);
--   * nenhuma coluna de cartão existe, nem deve existir;
--   * a chave de serviço vive apenas no ambiente do backend.
--
-- Aplicar no SQL Editor do Supabase. Tudo é idempotente
-- (`IF NOT EXISTS` / `ADD COLUMN IF NOT EXISTS`), então pode rodar
-- novamente sem apagar dado nenhum.

-- ─── pedidos ────────────────────────────────────────────────
create table if not exists public.pedidos (
  id            bigint generated by default as identity primary key,
  codigo        text not null unique,           -- número do pedido (GR-...)
  created_at    timestamptz not null default now(),
  updated_at    timestamptz,

  status                text not null default 'aguardando_pagamento',
  status_pagamento      text not null default 'aguardando',
  forma_pagamento       text not null default 'pix',

  subtotal_centavos     integer not null default 0,
  desconto_centavos     integer not null default 0,
  frete_centavos        integer,
  total_centavos        integer,
  cupom                 text,

  nome_cliente          text not null,
  email_cliente         text not null,
  telefone_cliente      text,
  cpf_cliente           text,
  endereco              jsonb not null default '{}'::jsonb,
  rastreio              text,
  observacoes           text,
  transportadora        text,
  rastreio_url          text,
  observacao_publica    text,

  mp_preference_id      text,
  mp_payment_id         text,
  mp_status             text,
  pago_em               timestamptz,

  -- Controle do e-mail transacional (Brevo).
  -- Guarda apenas QUANDO o e-mail saiu e o id da mensagem — serve para
  -- impedir envio duplicado. Nenhum conteúdo de e-mail é persistido.
  email_confirmacao_enviado_em timestamptz,
  email_confirmacao_id         text
);

-- Para bancos que já existiam antes da integração de e-mail:
alter table public.pedidos
  add column if not exists email_confirmacao_enviado_em timestamptz;
alter table public.pedidos
  add column if not exists email_confirmacao_id text;

-- Acompanhamento do pedido (rastreio.html): transportadora, link de
-- rastreio (somente HTTPS é gravado pelo backend) e a observação PÚBLICA
-- (que o cliente vê — diferente de `observacoes`, que é interna).
alter table public.pedidos
  add column if not exists transportadora text;
alter table public.pedidos
  add column if not exists rastreio_url text;
alter table public.pedidos
  add column if not exists observacao_publica text;

create index if not exists idx_pedidos_created_at on public.pedidos (created_at desc);
create index if not exists idx_pedidos_status on public.pedidos (status);
create index if not exists idx_pedidos_email_cliente on public.pedidos (email_cliente);

-- ─── pedido_itens ───────────────────────────────────────────
create table if not exists public.pedido_itens (
  id                    bigint generated by default as identity primary key,
  pedido_id             bigint not null references public.pedidos (id) on delete cascade,
  produto_id            text not null,
  nome                  text not null,
  tamanho               text,
  cor                   text,
  quantidade            integer not null default 1,
  preco_pix_centavos    integer not null default 0,
  preco_cartao_centavos integer not null default 0,
  created_at            timestamptz not null default now()
);

create index if not exists idx_pedido_itens_pedido on public.pedido_itens (pedido_id);

-- ─── order_events ───────────────────────────────────────────
-- Linha do tempo do pedido. Cada linha é UMA etapa realmente registrada
-- (criação, mudança de status, rastreio, observação pública). É a única
-- fonte da timeline exibida ao cliente em rastreio.html — nada é inferido
-- do status atual.
create table if not exists public.order_events (
  id          bigint generated by default as identity primary key,
  pedido_id   uuid not null references public.pedidos (id) on delete cascade,
  tipo        text not null default 'atualizacao',
  status      text,
  titulo      text,
  descricao   text,
  publico     boolean not null default true,
  criado_em   timestamptz not null default now()
);

create index if not exists idx_order_events_pedido on public.order_events (pedido_id, criado_em);

-- ─── cupons ─────────────────────────────────────────────────
-- Espelho consultável do catálogo. A AUTORIDADE continua sendo
-- dados/catalogo.js (META.cupons): se divergirem, vale o catálogo.
create table if not exists public.cupons (
  codigo                      text primary key,
  tipo                        text not null,
  valor                       integer not null default 0,
  ativo                       boolean not null default false,
  valor_minimo_centavos       integer not null default 0,
  validade                    timestamptz,
  limite_usos                 integer
);

-- ─── Segurança ──────────────────────────────────────────────
-- O backend usa a chave de serviço (server-side), que ignora RLS.
-- O frontend nunca deve ler/escrever estas tabelas diretamente.
-- Se no futuro o navegador precisar de acesso, crie políticas
-- explícitas por tabela — nunca desative RLS sem uma política.
alter table public.pedidos enable row level security;
alter table public.pedido_itens enable row level security;
alter table public.cupons enable row level security;
alter table public.order_events enable row level security;
