-- ═══════════════════════════════════════════════════════════════
-- GRACIOU — Migração incremental: ACOMPANHAMENTO DE PEDIDOS
-- Arquivo: supabase/migrations/20261007_acompanhamento_pedidos.sql
-- ═══════════════════════════════════════════════════════════════
--
-- O que esta migração faz:
--   1. acrescenta 3 colunas em public.pedidos:
--        transportadora      — nome da transportadora (texto)
--        rastreio_url        — link de rastreio (o backend só grava HTTPS)
--        observacao_publica  — observação que o CLIENTE vê (≠ observacoes,
--                              que continua sendo a nota interna)
--   2. cria a tabela public.order_events (linha do tempo do pedido).
--   3. cria os índices de apoio.
--
-- COMO APLICAR
--   Cole este arquivo inteiro no SQL Editor do Supabase e execute.
--   Rode UMA vez. É idempotente: rodar de novo não altera nem apaga dado.
--
-- SEGURANÇA / PRESERVAÇÃO
--   * Nenhum `update`, `delete` ou `drop` é executado.
--   * Os pedidos existentes permanecem exatamente como estão; as colunas
--     novas nascem NULL nos registros antigos.
--   * Nenhuma coluna de cartão é criada (não existe tal coluna no projeto).
--   * O backend grava/consulta `pedido_id` como STRING (o próprio uuid),
--     sem convertê-lo para número.
--   * Banco local (SQLite): as MESMAS colunas e a mesma tabela são
--     criadas automaticamente no boot por backend/db.js (função migrar).
--     No SQLite não há tipo uuid: `order_events.pedido_id` é TEXT, que
--     guarda o mesmo identificador (o id uuid em texto) sem conversão.
-- ═══════════════════════════════════════════════════════════════

-- ─── 1. Colunas novas em pedidos ────────────────────────────────
alter table public.pedidos
  add column if not exists transportadora text;

alter table public.pedidos
  add column if not exists rastreio_url text;

alter table public.pedidos
  add column if not exists observacao_publica text;

-- ─── 2. Tabela do histórico (linha do tempo) ────────────────────
-- ATENÇÃO ao tipo de `pedido_id`: no Supabase o id de public.pedidos é
-- uuid (`gen_random_uuid()`), então a FK também é uuid. Usar bigint aqui
-- quebra na criação da tabela ("column pedido_id is of type uuid but
-- expression is of type bigint").
create table if not exists public.order_events (
  id          bigint generated by default as identity primary key,
  pedido_id   uuid not null references public.pedidos (id) on delete cascade,
  tipo        text not null default 'atualizacao',
  status      text,
  titulo      text,
  descricao   text,
  publico     boolean not null default true,
  criado_em   timestamptz not null default now()
);

-- ─── 3. Índices de apoio ────────────────────────────────────────
-- A consulta pública casa número do pedido + e-mail.
create index if not exists idx_pedidos_email_cliente
  on public.pedidos (email_cliente);

-- A timeline é sempre lida por pedido, em ordem cronológica.
create index if not exists idx_order_events_pedido
  on public.order_events (pedido_id, criado_em);

-- ─── 4. RLS ─────────────────────────────────────────────────────
-- O backend usa a chave de serviço (server-side), que ignora RLS.
-- O navegador nunca lê estas tabelas diretamente. Mantemos RLS LIGADA
-- e sem política pública: assim o acesso pelo anon key continua negado.
alter table public.order_events enable row level security;
